{% set name = "bgcargo" %}
{% set version = "0.2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bgcArgo-{{ version }}.tar.gz
  sha256: 12d5c41ae11b9713ea09a3666334eceadb679de4fe011b30931cdf21c8ee57e0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - cmocean
    - gsw
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - python >=3.4
    - scipy
    - seaborn

test:
  imports:
    - bgcArgo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ArgoCanada/BGC-QC
  summary: A python library for quality control of BGC-Argo data
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - cgrdn
